---
- name: install packages
  hosts: all
  become: yes
  vars:
    packages:
      - vim
      - wget
      - tree
      - unzip
      - curl

  tasks:
    - name: install packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        " {{ packages }}"

